"""Clinical Reasoning Agent: orchestrates KnowledgeBase + RiskEngine +
RecommendationEngine into one structured, traceable output.

This agent is intentionally independent of the ML model. It only ever
receives an already-made prediction (disease_code + confidence) and patient
symptoms - it does not know or care whether that prediction came from the
real diagnostic model or from a mock (see mock/mock_prediction.json).

The reasoning it produces is assembled deterministically from templates and
the outputs of the risk/recommendation engines - it is not free-form
generated text, so every sentence in `reasoning` traces back to a specific
rule or knowledge base fact.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from src.config import RecommendationConfig, RiskConfig
from src.knowledge_base import KnowledgeBase
from src.recommendation_engine import Recommendation, RecommendationEngine
from src.risk_engine import RiskAssessment, RiskEngine

MEDICAL_DISCLAIMER = (
    "This report is generated by an AI-assisted clinical decision-support prototype "
    "and should not be considered a definitive medical diagnosis. Consultation with a "
    "qualified healthcare professional is recommended for clinical evaluation."
)


class ClinicalReasoningAgentError(Exception):
    """Raised when the agent receives a malformed request."""


@dataclass
class ClinicalReasoningOutput:
    disease_code: str
    display_name: str
    confidence: float
    confidence_band: str
    matched_symptoms: list[str]
    warning_signs: list[str]
    unmatched_symptoms: list[str]
    risk_level: str
    risk_score: int
    risk_factors: list[str]
    recommendation_category: str
    recommendation_text: str
    reasoning: str
    sources: list[dict[str, str]]
    taxonomy_note: str | None = None
    disclaimer: str = MEDICAL_DISCLAIMER


class ClinicalReasoningAgent:
    """Turns (disease_code, confidence, symptoms) into a full clinical reasoning result.

    Usage:
        agent = ClinicalReasoningAgent()
        result = agent.analyze("melanoma", 0.87, ["bleeding", "itching", "rapid growth"])

    Or with the nested request shape from the project spec:
        result = agent.analyze_request({
            "prediction": {"disease": "melanoma", "confidence": 0.87},
            "symptoms": ["bleeding", "itching", "rapid growth"],
        })
    """

    def __init__(
        self,
        knowledge_base: KnowledgeBase | None = None,
        risk_engine: RiskEngine | None = None,
        recommendation_engine: RecommendationEngine | None = None,
    ):
        self._kb = knowledge_base or KnowledgeBase()
        self._risk_engine = risk_engine or RiskEngine(self._kb, RiskConfig())
        self._recommendation_engine = recommendation_engine or RecommendationEngine(RecommendationConfig())

    def analyze(
        self, disease_code: str, confidence: float, symptoms: list[str] | None = None
    ) -> ClinicalReasoningOutput:
        """Run the full reasoning pipeline for one prediction.

        Raises UnknownDiseaseError if disease_code has no knowledge base entry,
        or RiskEngineError if confidence is not a valid number in [0, 1].
        """
        symptoms = symptoms or []

        entry = self._kb.get_disease(disease_code)
        risk = self._risk_engine.assess(disease_code, confidence, symptoms)
        recommendation = self._recommendation_engine.recommend(risk.risk_level)
        reasoning = self._build_reasoning(entry, risk, recommendation)

        return ClinicalReasoningOutput(
            disease_code=entry["disease_code"],
            display_name=entry["display_name"],
            confidence=risk.confidence,
            confidence_band=risk.confidence_band,
            matched_symptoms=risk.matched_symptoms,
            warning_signs=risk.matched_warning_signs,
            unmatched_symptoms=risk.unmatched_symptoms,
            risk_level=risk.risk_level,
            risk_score=risk.risk_score,
            risk_factors=risk.risk_factors,
            recommendation_category=recommendation.category,
            recommendation_text=recommendation.text,
            reasoning=reasoning,
            sources=entry["sources"],
            taxonomy_note=entry.get("taxonomy_note"),
        )

    def analyze_request(self, request: dict[str, Any]) -> ClinicalReasoningOutput:
        """Accepts the {"prediction": {"disease": ..., "confidence": ...}, "symptoms": [...]} shape."""
        if not isinstance(request, dict) or "prediction" not in request:
            raise ClinicalReasoningAgentError("Request must be a dict containing a 'prediction' key.")

        prediction = request["prediction"]
        if (
            not isinstance(prediction, dict)
            or "disease" not in prediction
            or "confidence" not in prediction
        ):
            raise ClinicalReasoningAgentError(
                "request['prediction'] must be a dict with 'disease' and 'confidence' keys."
            )

        symptoms = request.get("symptoms", [])
        if symptoms is not None and not isinstance(symptoms, list):
            raise ClinicalReasoningAgentError("request['symptoms'] must be a list of strings if provided.")

        return self.analyze(prediction["disease"], prediction["confidence"], symptoms)

    @staticmethod
    def _build_reasoning(
        entry: dict[str, Any], risk: RiskAssessment, recommendation: Recommendation
    ) -> str:
        """Assemble a deterministic, template-based reasoning narrative.

        Every sentence here is either a direct template fill-in or one of
        risk.risk_factors / recommendation.basis, which are themselves fully
        traceable to explicit rules. No free-form text generation is used.
        """
        lines = [
            f"The model predicted '{entry['display_name']}' with "
            f"{risk.confidence_band} confidence ({risk.confidence:.2f})."
        ]
        if entry.get("taxonomy_note"):
            lines.append(f"Note: {entry['taxonomy_note']}")
        lines.extend(risk.risk_factors)
        lines.append(
            f"Based on these factors, this case is assessed as {risk.risk_level} risk "
            f"(score={risk.risk_score})."
        )
        lines.append(recommendation.basis)
        lines.append(f"Recommended action: {recommendation.text}")
        return " ".join(lines)
